abbr -a -g zac 'zellij action'
abbr -a -g zs 'zellij -s'
abbr -a -g zsc 'zellij -l compact attach -c'
abbr -a -g zl 'zellij list-sessions'
abbr -a -g za 'zellij attach'
abbr -a -g zk 'zellij kill-session'
abbr -a -g zka 'zellij kill-all-sessions'
abbr -a -g zd 'zellij delete-session'
abbr -a -g zda 'zellij delete-all-sessions'
abbr -a -g ze 'zellij edit'
abbr -a -g zef 'zellij edit --floating'
abbr -a -g zr 'zellij run --'
abbr -a -g zrf 'zellij run --floating --'
